"""must_change_password

Revision ID: 0ec9a06a5084
Revises: 0f9d269f834a
Create Date: 2026-06-10 23:52:11.206530
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0ec9a06a5084'
down_revision: Union[str, None] = '0f9d269f834a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
