"""submission pipeline fields

Revision ID: 0f9d269f834a
Revises: 41df8728e658
Create Date: 2026-06-10 22:23:43.560688
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f9d269f834a'
down_revision: Union[str, None] = '41df8728e658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('external_application_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('submission_evidence', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('submission_evidence')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('confirmation_url')
        batch_op.drop_column('external_application_id')
        batch_op.drop_column('submission_status')

    # ### end Alembic commands ###
