"""initial schema

Revision ID: 41df8728e658
Revises: 
Create Date: 2026-06-10 19:16:13.814229
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '41df8728e658'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portal', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('salary_inr', sa.String(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('manual_required', sa.Boolean(), nullable=True),
    sa.Column('job_url_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_job_url_hash'), ['job_url_hash'], unique=False)

    op.create_table('job_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roles', sa.Text(), nullable=True),
    sa.Column('locations', sa.Text(), nullable=True),
    sa.Column('job_types', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_filters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_filters_id'), ['id'], unique=False)

    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_resets_token_hash'), ['token_hash'], unique=False)

    op.create_table('portal_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portal_name', sa.String(), nullable=False),
    sa.Column('encrypted_email', sa.Text(), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portal_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portal_credentials_id'), ['id'], unique=False)

    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('parsed_name', sa.String(), nullable=True),
    sa.Column('parsed_email', sa.String(), nullable=True),
    sa.Column('parsed_phone', sa.String(), nullable=True),
    sa.Column('parsed_location', sa.String(), nullable=True),
    sa.Column('parsed_skills', sa.Text(), nullable=True),
    sa.Column('parsed_experience', sa.Integer(), nullable=True),
    sa.Column('parsed_education', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_id'))

    op.drop_table('resumes')
    with op.batch_alter_table('portal_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portal_credentials_id'))

    op.drop_table('portal_credentials')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_resets_id'))

    op.drop_table('password_resets')
    with op.batch_alter_table('job_filters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_filters_id'))

    op.drop_table('job_filters')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_job_url_hash'))
        batch_op.drop_index(batch_op.f('ix_applications_id'))

    op.drop_table('applications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
