"""user seeker_type

Revision ID: 71c6a7cbcb4e
Revises: ef54e06ed042
Create Date: 2026-06-11 09:30:24.788855
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '71c6a7cbcb4e'
down_revision: Union[str, None] = 'ef54e06ed042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeker_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('seeker_type')

    # ### end Alembic commands ###
