"""b1 indexes auth-revocation email-verify submission-queue

Revision ID: ef54e06ed042
Revises: 0ec9a06a5084
Create Date: 2026-06-11 00:14:30.633099
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ef54e06ed042'
down_revision: Union[str, None] = '0ec9a06a5084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submission_payload', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_applications_submission_status'), ['submission_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_applications_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index('ix_applications_user_substatus', ['user_id', 'submission_status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verify_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email_verify_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_version')
        batch_op.drop_column('email_verify_expires')
        batch_op.drop_column('email_verify_hash')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('ix_applications_user_substatus')
        batch_op.drop_index('ix_applications_user_status')
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_applications_submission_status'))
        batch_op.drop_column('submission_payload')
        batch_op.drop_column('submission_attempts')

    # ### end Alembic commands ###
